---
host: 127.0.0.1:221
tasks:
  - module: file
    args:
      path: /tmp/depi/test
      owner: ubuntu
      group: ubuntu
      perms: 700
      state: directory
  - module: file
    args:
      path: /tmp/depi/test/wonolo.txt
      owner: ubuntu
      group: ubuntu
      mode: 770
      state: touch
  - module: file
    args:
      path: /tmp/depi/test/wonolo2.txt
      owner: ubuntu
      group: ubuntu
      mode: 777
      state: file
      src: Dockerfile-ubuntu
