---
host: 127.0.0.1:221
tasks:
  - module: package
    args:
      name: nginx
      state: present
  - module: file
    args: 
      path: /var/www/html/index.html
      src: index.html
      owner: www-data
      group: www-data
      mode: 777
      state: file
  - module: service
    args:
      name: nginx
      state: start
